### ISSUE TITLE
help on usage

### ISSUE THREAD

**Issue by daimagine** [iazi/ngMapAutocomplete#4]
Thanks for this directives, I found it useful since its already on bower

However, I have cloned original example in here: [plunkr](http://plnkr.co/edit/GE34ojss9xMGm0024FvM?p=preview) but it seems not working.
could you help me?

**Comment by joanrodriguez** [comment]
It works just fine on my computer:

![image](https://cloud.githubusercontent.com/assets/10894843/11846405/c7930d76-a418-11e5-8922-e5fe9fa26665.png)

**Comment by daimagine** [comment]
I figured it out that I used wrong tag `ng-autocomplete`, it should be `ng-map-autocomplete` and it works like a charm.

thank you
